repos:
  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        args: [--check]
        additional_dependencies:
          - mdformat-footnote
          - mdformat-mkdocs

  - repo: local
    hooks:
      - id: mkdocs-build
        name: mkdocs build
        entry: .venv/bin/mkdocs build -s
        language: system
        files: ^(mkdocs.yaml|docs/)
        pass_filenames: false
